name: location_iq
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/takara-homes/location_iq

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.15.0
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^6.0.0
  test: ^1.24.0
